# This is notebook for CodeSignal practice tests

In [27]:
import numpy as np

# Rotate Matrix

You are given an n x n 2D matrix that represents an image. Rotate the image by 90 degrees (clockwise).


In [32]:
def rotateImage(a):
    n = len(a)
    m1 = n//2
    m2 = m1 + n % 2
    
    for i in range(m2):
        for j in range(m1):
            tem = a[i][j]
            a[i][j] = a[n-1-j][i]
            a[n-1-j][i] = a[n-1-i][n-1-j]
            a[n-1-i][n-1-j] = a[j][n-1-i]
            a[j][n-1-i] = tem
            
    return a

In [29]:
a = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
print(np.matrix(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


the output should be
rotateImage(a) = 

In [33]:
r = rotateImage(a)
print(np.matrix(r))

[[7 4 1]
 [8 5 2]
 [9 6 3]]


In [7]:
a = "."
int(a)

ValueError: invalid literal for int() with base 10: '.'

# First Duplicate

Given an array a that contains only numbers in the range from *1* to *a.length*, find the first duplicate **number** for which the second occurrence has the minimal index. In other words, if there are more than 1 duplicated numbers, return the **number** for which the second occurrence has a smaller index than the second occurrence of the other number does. If there are no such elements, return *-1*.

In [34]:
def firstDuplicate(a):

    res = -1
    maxa = max(a) + 1
    count = [0]*maxa
    
    for n in a: 
        count[n] += 1
        if count[n] == 2:
            res = n
            break    

    return res

In [35]:
a = [2, 1, 3, 5, 3, 2]
r = firstDuplicate(a)
print(r)

3


# First non repeating character

Given a string *s* consisting of small English letters, find and return the first instance of a non-repeating character in it. If there is no such character, return *'_'*.

In [36]:
def firstNotRepeatingCharacter(s):
    
    a = 'abcdefghijklmnoqrstuvwxyz'
    ch = [c for c in a] # make a list of the alphabet
    l = len(a) # for sure length a = 26
    
    count = [0]*l # initiate counting
    loc = [0]*l # initiate locations
    
    res = '_' # default result if nothing happens
    
    ls = len(s)
    
    for n in range(ls):
        c = s[n]
        for m in range(l): 
            if c == ch[m]: 
                count[m] += 1
                loc[m] = n
                break
                
    minl = ls
    
    for n in range(l):
        if count[n] == 1:
            if minl > loc[n]: 
                minl = loc[n]
                res = ch[n]
                
    return res
    
    

In [38]:
s = "abacabad"
fc = firstNotRepeatingCharacter(s)
print(fc)

c


# Compose ranges

Given a sorted integer array that does not contain any duplicates, return a summary of the number ranges it contains.

In [43]:
def composeRanges(nums):
    
    length = len(nums)
    if length == 0:
        return []
    
    elif length == 1:
        return [str(nums[0])]
    
    else:
        res=[]
        a = nums[0]
        b = a
        for n in range(1,length): 
            c = nums[n]
            if c < b + 2:
                if n < length - 1:
                    b = c
                    pass
                else:
                    s = str(a) + "->" + str(c)
            
                    res.append(s)
            else:
                s = str(a)
                if b > a:
                    s = s + "->" + str(b)
                res.append(s)
                a = c
                b = c 
                if n == length - 1:
                    res.append(str(c))
                    
        return res
                    
                    

In [44]:
nums = [-1, 0, 1, 2, 6, 7, 9]
r = composeRanges(nums)
print(r)

['-1->2', '6->7', '9']


# House robber

You are planning to rob houses on a specific street, and you know that every house on the street has a certain amount of money hidden. The only thing stopping you from robbing all of them in one night is that adjacent houses on the street have a connected security system. The system will automatically trigger an alarm if two adjacent houses are broken into on the same night.

Given a list of non-negative integers *nums* representing the amount of money hidden in each house, determine the maximum amount of money you can rob in one night without triggering an alarm.

In [45]:
def houseRobber(nums):
    length = len(nums)
    if length <=1:
        return sum(nums)
    elif length == 2:
        return max(nums)
    elif length == 3:
        return max(nums[0] + nums[2], nums[1])
    elif length > 3:
        a = nums[0]
        b = max(a,nums[1])
        c = max(nums[0] + nums[2], nums[1])
        
        for n in range(3,length):
            d = max(nums[n] + b, nums[n-1] + a)
            a = b
            b = c
            c = d
            
        return max(b, c)
        

In [46]:
nums = [232, 161, 89, 177, 117, 212, 126, 247, 155, 197, 88, 217, 81, 207]
r = houseRobber(nums)
print(r)

1489


# Climb stairs

You are climbing a staircase that has *n* steps. You can take the steps either 1 or 2 at a time. Calculate how many distinct ways you can climb to the top of the staircase.

In [47]:
def climbingStairs(n):
    if n == 1:
        return 1
    
    elif n == 2: 
        return 2

    else:
        a = 1
        b = 2
        for i in range(n-2):
            c = b
            b = a + b
            a = c 
        return b
    
n = 20
print(climbingStairs(n))

10946
